const EMAIL_SENDER = 'info@dashinbetween.com';
const EMAIL_PROMO_TEMPLATE = 'd-0fb9f8101a4a4a838af556db2bbafef0';
const PROMO_BUY1GET1 = 'BUY1GET1';
const PROMO_BUY2GET1 = 'BUY2GET1';

module.exports = {
  EMAIL_SENDER,
  EMAIL_PROMO_TEMPLATE,
  PROMO_BUY1GET1,
  PROMO_BUY2GET1,
}